In [1]:
import numpy as np

In [2]:
m = np.random.rand(20,4)

In [3]:
m

array([[0.33957441, 0.96474423, 0.46585261, 0.64151007],
       [0.0085919 , 0.72867575, 0.68220467, 0.67523703],
       [0.50524275, 0.67934039, 0.96546459, 0.43778291],
       [0.49304983, 0.6014004 , 0.87410439, 0.08034608],
       [0.23591023, 0.23550823, 0.07860125, 0.16488782],
       [0.13996807, 0.38838541, 0.8156364 , 0.08821014],
       [0.5886785 , 0.82086823, 0.38954253, 0.20572974],
       [0.30187796, 0.93027839, 0.64167154, 0.09396737],
       [0.95863987, 0.20101062, 0.03202015, 0.00250245],
       [0.94751918, 0.95128384, 0.58037501, 0.58706885],
       [0.55763337, 0.54337178, 0.59285288, 0.16261497],
       [0.10605591, 0.42114086, 0.02676221, 0.70948936],
       [0.42574405, 0.67866647, 0.23810215, 0.25674942],
       [0.89022601, 0.93579964, 0.81978965, 0.26445228],
       [0.92469109, 0.03644981, 0.07686009, 0.28193938],
       [0.78531521, 0.62542716, 0.65673879, 0.86240827],
       [0.86308518, 0.84177945, 0.92937093, 0.20385847],
       [0.38265899, 0.19721059,

In [4]:
x = np.random.rand(120,20)

In [5]:
p = x.dot(m)

In [6]:
p

array([[4.93706173, 6.03694617, 5.09662172, 3.83481259],
       [6.02733961, 6.42971159, 5.69172129, 4.34451068],
       [5.97151054, 5.59691993, 5.19537683, 4.2066256 ],
       [4.41467866, 4.40510252, 3.58608141, 3.89537702],
       [7.91433016, 7.23158171, 6.261472  , 4.8454273 ],
       [5.13355279, 5.8636711 , 5.08205489, 4.94612028],
       [3.89906529, 4.44577972, 3.69685171, 3.00906063],
       [4.86017501, 4.32584779, 3.65224213, 3.73808866],
       [6.34387576, 6.75167524, 5.69315862, 4.72227093],
       [6.07803426, 6.09214445, 5.45566189, 4.25716039],
       [4.96038596, 5.70639333, 4.99417702, 3.70926223],
       [5.71291558, 5.24095264, 5.19032256, 3.52971113],
       [4.90683419, 4.72171659, 4.22289727, 3.58329374],
       [4.87355301, 5.50102525, 5.34510763, 3.47703795],
       [6.22558591, 6.14640463, 5.2026979 , 4.42464777],
       [5.74949345, 5.4131534 , 4.82856137, 3.89715516],
       [4.72758566, 5.50120752, 4.83520929, 3.70382094],
       [5.31652281, 5.16689767,

In [7]:
class ELM(object):
    def init_weights(self,c,h):
         return np.random.rand(c,h)
    def insert_bias(self,m):
        return m
    def pinv(self,m):
        return np.linalg.pinv(m)

In [8]:
elm  = ELM()

In [9]:
 wh = elm.init_weights(20,5)

In [10]:
elm.pinv(wh)

array([[ 0.05477519,  0.11950944,  0.1917874 , -0.2206668 , -0.17487579,
        -0.24407002, -0.01581971,  0.07158354,  0.03826612,  0.22178742,
        -0.01747567,  0.05989877, -0.17836118,  0.05571428,  0.03726297,
        -0.01373123,  0.05982446, -0.00066213,  0.29188731,  0.1292266 ],
       [ 0.12502869,  0.23859761,  0.00812448,  0.00138716, -0.188687  ,
         0.19376627, -0.04020068, -0.27604485,  0.23304911, -0.00191047,
        -0.28808712,  0.20042393,  0.18613179,  0.13101421,  0.15786879,
         0.07676728,  0.31326675, -0.11786638, -0.17231088, -0.59482348],
       [-0.14329832, -0.11503203, -0.09807191,  0.21162228,  0.37928119,
         0.06274994, -0.10838838,  0.05605983,  0.06950977, -0.16757481,
         0.44641879, -0.10320407,  0.02533741,  0.00974795, -0.12184342,
        -0.04750069, -0.08193778, -0.06315446, -0.16517017,  0.45910054],
       [-0.01243706, -0.26947229,  0.0233096 ,  0.22309472,  0.00337291,
        -0.06225593,  0.12629954,  0.23182296, -

In [11]:
a = [[1,2,3],[2,4,7],[9,8,5]]
from util import *


In [12]:
addBias(a)

array([[1, 2, 3, 1],
       [2, 4, 7, 1],
       [9, 8, 5, 1]])