In [1]:
import numpy as np

In [6]:
m = np.random.rand(20,4)

In [7]:
m

array([[0.68470535, 0.57085919, 0.61471751, 0.86557604],
       [0.70631759, 0.93240322, 0.42585192, 0.20539529],
       [0.79557636, 0.02687119, 0.41602251, 0.13652021],
       [0.57134406, 0.05708978, 0.49013772, 0.04376106],
       [0.02227002, 0.3749714 , 0.70853461, 0.56594642],
       [0.52815215, 0.46565499, 0.74237523, 0.25395605],
       [0.01213731, 0.78775707, 0.0287491 , 0.82691381],
       [0.06204993, 0.23667078, 0.03173541, 0.80881658],
       [0.78521285, 0.1684965 , 0.95867019, 0.17432245],
       [0.14171575, 0.26459878, 0.87519086, 0.82035932],
       [0.90837865, 0.75644384, 0.50361274, 0.30659912],
       [0.03827201, 0.60718549, 0.99711214, 0.54702602],
       [0.5946226 , 0.22621197, 0.52889538, 0.80432969],
       [0.57092715, 0.33394791, 0.19234404, 0.59893997],
       [0.5390198 , 0.46089858, 0.71496984, 0.85016854],
       [0.59861951, 0.2551023 , 0.82242628, 0.13131416],
       [0.5425039 , 0.27300306, 0.06022227, 0.34319405],
       [0.15476707, 0.74473487,

In [4]:
x = np.random.rand(120,20)

In [8]:
p = x.dot(m)

In [9]:
p

array([[5.347689  , 3.78675771, 5.34902584, 4.82335024],
       [4.75142115, 5.00885505, 6.01760975, 5.70076658],
       [5.75011731, 4.2512458 , 6.72464578, 4.61693741],
       [4.29690642, 3.52821405, 5.00218091, 4.69031236],
       [4.80183327, 4.33557618, 5.69614067, 5.83124284],
       [3.32427762, 3.3650538 , 4.53903523, 3.86102944],
       [4.3067045 , 3.66435787, 4.5937554 , 4.12237521],
       [5.27876691, 4.51389075, 5.51808642, 5.7545169 ],
       [4.14548027, 3.87424375, 4.32573631, 4.79281885],
       [4.15144758, 2.98877694, 5.13949293, 4.69451185],
       [4.58216863, 4.14499611, 5.55231232, 5.50393694],
       [4.90570627, 4.3169783 , 6.22014185, 5.9295296 ],
       [5.28516374, 4.42056185, 6.19881279, 4.94617107],
       [5.09960247, 4.87389476, 5.51718633, 5.35857914],
       [5.37190472, 4.42748915, 5.76044851, 4.98654488],
       [5.91996582, 4.63534638, 6.86796372, 5.82320117],
       [5.66228982, 4.58615721, 6.42243417, 6.0906454 ],
       [4.94726135, 3.89429302,

In [21]:
class ELM(object):
    def init_weights(self,c,h):
         return np.random.rand(c,h)
    def insert_bias(self,m):
        return m
    def pinv(self,m):
        return np.linalg.pinv(m)

In [22]:
elm  = ELM()

In [23]:
 wh = elm.init_weights(20,5)

In [24]:
elm.pinv(wh)

array([[-0.14349518,  0.04916066, -0.11631804, -0.02815818, -0.07727803,
         0.25569757,  0.27257022,  0.03981837, -0.25285038,  0.13387025,
        -0.02506906,  0.47367151, -0.2413031 ,  0.09185502, -0.01867782,
        -0.01979086,  0.10643649, -0.33318701, -0.06879421,  0.3441674 ],
       [-0.01008615, -0.20802982, -0.14001133,  0.10187708,  0.23462177,
        -0.21784959,  0.1272053 , -0.25559957,  0.39682322,  0.35596609,
        -0.17346716,  0.20460726,  0.31729092, -0.14242211,  0.10332341,
        -0.04716704,  0.01310802,  0.09695137,  0.05469485, -0.23285031],
       [ 0.15315325, -0.05344907,  0.32738382,  0.07686627,  0.1640531 ,
         0.55974119, -0.20170528,  0.04189556, -0.02405574, -0.19166806,
         0.07356808, -0.28906432,  0.05141746,  0.15938172,  0.15641151,
        -0.31706185,  0.01403812, -0.06031363, -0.03033043, -0.18058488],
       [ 0.22402949,  0.42273006,  0.10915732, -0.27206514, -0.25861152,
        -0.00420855, -0.3002002 ,  0.43321381,  